### ISSUE TITLE
Split into C++ library and Python packages

### ISSUE THREAD

**Issue by garth-wells** [conda-forge/adios2-feedstock#54]
It would be helpful if the ADIOS2 package was split in to a (1) C++ library package and a (2) Python package. The issue is that packages that depend on the ADIOS2 C++ interface/library but not on Python get a transitive dependency on Python. See, for example, https://github.com/conda-forge/fenics-dolfinx-feedstock/issues/15.

**Comment by minrk** [comment]
Took a stab at this in #55. Works for local builds at least (mac-arm).
