### ISSUE TITLE
2.9.0 not picked up in openPMD-api

### ISSUE THREAD

**Issue by ax3l** [conda-forge/adios2-feedstock#78]
Hi @minrk,

I am trying to create a build of openPMD-api with ADIOS 2.9.0 included:
  https://github.com/conda-forge/openpmd-api-feedstock/pull/106

but somehow it still pulls in the 2.8.3 ADIOS2 builds. Do you understand why it does that?

**Comment by minrk** [comment]
very likely to be a pinned dependency somewhere, I'll see if I can figure it out

**Comment by ax3l** [comment]
@minrk thank you, let me know what you find :)

**Comment by ax3l** [comment]
btw, do we need to declare pinning of versions in the package itself?

re: https://github.com/conda-forge/adios2-feedstock/pull/76#issuecomment-1671850712

**Comment by minrk** [comment]
> btw, do we need to declare pinning of versions in the package itself?


Yes, we [have that](https://github.com/conda-forge/adios2-feedstock/blob/a8945d8818f0ff2ce36c4decba5da0e3935e7838/recipe/meta.yaml#L61). Any package that links adios2 (or libadios2) will have a runtime dependency pinned to the patch version and mpi variant.

It was the hdf5 1.14.1 migration - adios2 had been updated to 1.14.1, while openpmd-api was still on 1.12. I'm not sure why the bot never issued a PR, but claimed that openpmd-api had been migrated, when it hadn't.  https://github.com/conda-forge/openpmd-api-feedstock/pull/107 should fix it.
